modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Chitak985/ad-astra-PromisedWorlds/issues"

[[mods]]
    modId="planetsplus"
    version="0.0.1"
    displayName="Promised Worlds Ad Astra"
	displayURL="https://github.com/Chitak985/ad-astra-PromisedWorlds"
    logoFile="image.png"
    authors="Chitak985YT: Owner/Dev"
    credits="Chitak985YT: Owner/Dev"
    description="Adds planets from the Promised Worlds KSP mod!"

[[dependencies.planetsplus]]
    modId="forge"
    mandatory=false
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.planetsplus]]
    modId="neoforge"
    mandatory=false
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"	
[[dependencies.planetsplus]]
    modId="ad_astra"
    mandatory=true
    versionRange="[1.15.19,1.16.6,)"
    ordering="NONE"
    side="BOTH"		
[[dependencies.planetsplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"